---
all:
  hosts:
    proxmox:
      ansible_host: 192.168.122.10
      ansible_user: me
      ansible_become_password: "{{ vault_root_password }}"
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
