---
# Bridged networking â€” VMs will get IPs from the same network

- name: Deploy bridge network configuration
  ansible.builtin.template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    mode: "0644"
    backup: true
  notify: Restart networking

- name: Enable IP forwarding
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "1"
    sysctl_set: true
    reload: true
  loop:
    - net.ipv4.ip_forward
    - net.ipv6.conf.all.forwarding
  notify: Reload sysctl
